dist: trusty
sudo: false
env:
- DIR=Tex FILE=main
addons:
  apt:
    packages:
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - cm-super
    - dvipng
    - texlive-latex-recommended
    - texlive-lang-german
    - texlive-science
    - texlive-math-extra
    - texlive-font-utils
    - latex-xcolor
before_script:
- wget -qO- http://ftp.icm.edu.pl/packages/ghostscript/binaries/ghostscript-9.15-linux-x86_64.tgz|tar
  xvz --strip=1&&mv gs-915-linux_x86_64 gs&&chmod +x gs
- PATH=$PWD:$PATH
script:
- cd $DIR
- pdflatex -interaction=nonstopmode -halt-on-error $FILE
- bibtex $FILE || true 
- pdflatex -interaction=nonstopmode -halt-on-error $FILE
- pdflatex -interaction=nonstopmode -halt-on-error $FILE
- gs -o compressed.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress  -dColorConversionStrategy=/LeaveColorUnchanged  -dDownsampleColorImages=false
  -dEmbedAllFonts=true  -dCompressFonts=true -dSubsetFonts=false -dNOPAUSE -dBATCH
  $FILE.pdf
deploy:
  provider: releases
  api_key:
    secure: LGZSz6q6Ve3kZp1FH2JNLqzby341NwIVmPjZUl09bB4E8XQn9qVc/nNy1rcTyiowkI676kmyOt/t+pX2DfpKQuJPS5JX66LfO+WIdCNrnnF/xPsaf2JhcozYaGOJXJ+SrUqZxCiQhdsxuY223SGhHEPwOtHAbxILlI51zsEPv4xNTV8a2jM/Vm8yuMl9x/p/kuMzTyEqAa3ivqoW0Hdc0dFFAQl+vFw0JOWoUbNuCRKZ3ST4jgtzuBPsAgOn/Fs2aH164Eg2OPLXLns5v3SZNygYYVbOlroklzBekTS79tlTQHR6g5yHJMmgkCdXAbaYcGf4fVmP01yxJ8f7OVbgf77IfxcqKN1xf258H7m7DYzHz3Y0jcBBHn3R9tNGMd15mZzndWFSoglGVdzly+/aqaZlUdSXFtji7bRKY/pwrXY0ylPX+oXCRS6foGxKJpwuTHk5n/1fF2WCL0pnYVnrR8gxgrlaV0Rhvu24Q1YkYT1VPhnP1SEL53pRtfk7QlhJoZEdoXm0krWa+H8ZDCbto5RIPulZt6I4c5kcUxOkeXL7Ni7JkejSRiA7DSAA/KZQUcevwWlnTQtpRPvJRcrLTHpITRR+IsvVxo/o8/hM21jOPKXygUCfkdr5ugr3l1xwyHBty43xN6ZI2I90KtFUGk6H/CO9SUrCu/2/tCPOzDE=
  file: compressed.pdf
  on:
    repo: fzimmermann89/msc
  skip_cleanup: 'true'
