name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Get ghostscript
        run: sudo apt-get install ghostscript 
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: pdflatex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: Tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape  
        
      - name: bibtex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: Tex
          compiler: bibtex
          args: ''
          
      - name: pdflatex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: Tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape     
          
      - name: pdflatex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: Tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape      
          
      - run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
